### ISSUE TITLE
Not able to lock

### ISSUE THREAD

**Issue by ghost** [lemanhtien/MTSlideToOpen#2]
am trying with **"slide to lock"**.
while tapping & dragging on thumnailImageView am notable to close the lock.
it is coming back again to same position. tried multiple times

**Comment by lemanhtien** [comment]
If you want to keep the thumbnail in lock position, don't call function `resetStateWithAnimation` in the delegate.
You can see in my example project

```
    func mtSlideToOpenDelegateDidFinish(_ sender: MTSlideToOpenView) {
        let alertController = UIAlertController(title: "", message: "Done!", preferredStyle: .alert)
        let doneAction = UIAlertAction(title: "Okay", style: .default) { (action) in
            sender.resetStateWithAnimation(false)
        }
        alertController.addAction(doneAction)
        self.present(alertController, animated: true, completion: nil)
        
    }
```

Please comment the line `sender.resetStateWithAnimation(false)`

**Comment by ghost** [comment]
i got one more issue here

am using multiple English, Arabic languages in my app

While using *english* the slidingButton is working fine. And i can swipe
the *thumNailImage* from *left to right*.

But, when am using *Arabic*, the slidingButton is not working. am not able
to swipe the *thumNailImage* from *right to left*

Could you help me regarding this issue



-- 
Thanks & Regards
Bhanuteja
