### ISSUE TITLE
No slide completion event after device orientation change

### ISSUE THREAD

**Issue by francoisdeberry** [lemanhtien/MTSlideToOpen#5]
Hi,
I'm having trouble with the slider. After a device orientation change, the slider's completion event is not triggered and the thumbnail go beyond the right edge.
Seems to me that the subview's constraints got broken.
Plus, a broken constraint warning shows up on the slider's label when orientation changes.

Can you confirm ?
Thanks !

Edit : I was trying to instantiate it via storyboard and it seems to be the problem... it works when loaded programmatically.

**Comment by lemanhtien** [comment]
Thank you for your report. I just updated the code :blush:
Please try the newest version and let me know if you face any isssue :tada:
