### ISSUE TITLE
Adjusting Sliding Circles Size and Image Size?

### ISSUE THREAD

**Issue by jackjpark** [lemanhtien/MTSlideToOpen#6]
Hey,

I am integrating the library and want to reduce the size of the draggable circle to fit it inside the slider bar rather than equal or larger.

I also need to set a specific frame size for the image inside the circle

Are either of these things possible? as i cant see a way to add an image frame size or to shrink / size the draggable circle.

Thanks

**Comment by lemanhtien** [comment]
Hi @jackjpark,
Thank you for using this library. 
In this current version, I don't support these 2 functions. But I think it can easily to achieve that.
- For the first one, needed to add a property to update the constraint of the thumbnail with the view
- For the second, the circle is just a UIImageView, actually it's public property, so you can add another UIImageView as a subview and constraint to the parent UIImageView

**Comment by iasonasiasonos** [comment]
Hey any news on the first one of how can we achieve this?

**Comment by lemanhtien** [comment]
@iasonasiasonos The first one is done on above merge request 😆

**Comment by lemanhtien** [comment]
@iasonasiasonos Can try the 1.3.0 for this feature.
@jackjpark Right now I dont support setting frame for image. Will consider t o do it in the future 😄
